### ISSUE TITLE
Wrong colorization in Yaml files

### ISSUE THREAD

**Issue by sugdyzhekov** [wholroyd/vscode-jinja#3]
Could you check following examples? Looks like Jinja colorization works wrong.

Example 1:
![example1](https://cloud.githubusercontent.com/assets/8955225/16642881/e27a2d32-4430-11e6-914e-5faf4d57e9aa.png)

``` yaml
setup_plesk:
  cmd.run:
    - name: |
        PSA_PASSWORD={{ pass }} /usr/sbin/plesk bin init_conf --init -shared_ips add:{{ ip }} -license_agreed true -admin_info_not_required true -send_announce false -send_tech_announce false -hostname {{ fqdn }} -passwd "" -company plesk.ru -name Administrator -email {{ email }}
        ...
```

Example 2:
![example2](https://cloud.githubusercontent.com/assets/8955225/16642880/e260e0e8-4430-11e6-93b3-14ef737b1a05.png)

``` yaml
setup_plesk:
  cmd.run:
    - name: PSA_PASSWORD={{ pass }} /usr/sbin/plesk bin init_conf --init -shared_ips add:{{ ip }} -license_agreed true -admin_info_not_required true -send_announce false -send_tech_announce false -hostname {{ fqdn }} -passwd "" -company plesk.ru -name Administrator -email {{ email }}
```

Example 3:
![example3](https://cloud.githubusercontent.com/assets/8955225/16642837/88d2576e-4430-11e6-8139-a50a9f33c9d0.png)

``` yaml
create_default_subscription:
  cmd.run:
    - name: /usr/sbin/plesk bin subscription -c {{ fqdn }} -hosting true -ip {{ ip }} -login support -passwd $(/usr/bin/openssl rand -base64 12)
    - unless: /usr/sbin/plesk bin subscription -i {{ fqdn }} &>/dev/null
```
